name: .NET Test

on:
  workflow_run:
    workflows: [".NET Build"]
    types:
      - completed

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
